---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /ansible
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /infra/terraform/cloudflare/state-bootstrap
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /infra/terraform/cloudflare/apptolast-dns
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /infra/terraform/netcup/perimeter
    schedule:
      interval: weekly
