---
- name: Enable Docker IPv4 forwarding
  ansible.builtin.command:
    argv:
      - /usr/sbin/sysctl
      - -w
      - net.ipv4.ip_forward=1
  changed_when: true
  when:
    - not ansible_check_mode

- name: Restart Docker
  ansible.builtin.systemd_service:
    name: docker.service
    state: restarted
  listen: Restart Docker
  when:
    - not ansible_check_mode

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  listen: Reload systemd
  when:
    - not ansible_check_mode
