---
organizationweb:
  schema_version: 1
  stack_name: organizationweb
  release: 4d9469a1a3db10e02b40de648202a3b97511feef
  hostname: organizacion.apptolast.com
  edge_network: apptolast-edge-organizationweb
  data_root: /srv/organizationweb
  images:
    backend: "ocholoko888/organizationweb-api@sha256:\
      474db9687be9c083fc92f59c65f58798bf0efc797b4ff96a3ad02432486cf72a"
    web: "ocholoko888/organizationweb-web@sha256:\
      18d04ce974abbd00d15daa47e73258b4f742aac31f025d8784fb4cabea274d8f"
    postgres: "postgres@sha256:\
      9ae4e8f8d0284836a505f0b2e825144e32e20499856e7dc5f7b99e19d10eedd6"
    rabbitmq: "rabbitmq@sha256:\
      ac1201d1dc227779d93c607f976e7f9156fd5b551ee5ff7946cab6c242091bf3"
  secrets:
    db_username: organizationweb-db-username-v1
    db_password: organizationweb-db-password-v1
    auth_username: organizationweb-auth-username-v1
    auth_password: organizationweb-auth-password-v1
    rabbitmq_username: organizationweb-rabbitmq-username-v1
    rabbitmq_password: organizationweb-rabbitmq-password-v1
    rabbitmq_config: organizationweb-rabbitmq-config-v1
