---
organizationweb:
  schema_version: 1
  stack_name: organizationweb
  release: 4d34b9c66cc024d40e163672819934fa38ebaf09
  hostname: organizacion.apptolast.com
  edge_network: apptolast-edge-organizationweb
  data_root: /srv/organizationweb
  images:
    backend: "ocholoko888/organizationweb-api@sha256:\
      f862dedec1e1533d95743344b710e58f7fba88fad9a9b90b10c586967a2a01ef"
    web: "ocholoko888/organizationweb-web@sha256:\
      0c2bb3dfcd48dceb0e469a4c8cf70cb7b22ed8d3aa7c48ea068fc6e94452dd7a"
    postgres: "postgres@sha256:\
      9ae4e8f8d0284836a505f0b2e825144e32e20499856e7dc5f7b99e19d10eedd6"
    rabbitmq: "rabbitmq@sha256:\
      ac1201d1dc227779d93c607f976e7f9156fd5b551ee5ff7946cab6c242091bf3"
  secrets:
    db_username: organizationweb-db-username-v1
    db_password: organizationweb-db-password-v1
    auth_username: organizationweb-auth-username-v1
    auth_password: organizationweb-auth-password-v1
    rabbitmq_username: organizationweb-rabbitmq-username-v1
    rabbitmq_password: organizationweb-rabbitmq-password-v1
    rabbitmq_config: organizationweb-rabbitmq-config-v1
