---
organizationweb:
  schema_version: 1
  stack_name: organizationweb
  release: 4c74e183e49afa6d280115b399dbaffedc7bfe7f
  hostname: organizacion.apptolast.com
  edge_network: apptolast-edge-organizationweb
  data_root: /srv/organizationweb
  images:
    backend: "ocholoko888/organizationweb-api@sha256:\
      313446ebc241ec2812c2d5dcbfb5618a3bc398253e9b4e78b55b6730c650216d"
    web: "ocholoko888/organizationweb-web@sha256:\
      4ebd36d9a2e57f647f4ed72798ebe4039b46756659765913cc67c9b71ddf0186"
    postgres: "postgres@sha256:\
      9ae4e8f8d0284836a505f0b2e825144e32e20499856e7dc5f7b99e19d10eedd6"
    rabbitmq: "rabbitmq@sha256:\
      ac1201d1dc227779d93c607f976e7f9156fd5b551ee5ff7946cab6c242091bf3"
  secrets:
    db_username: organizationweb-db-username-v1
    db_password: organizationweb-db-password-v1
    auth_username: organizationweb-auth-username-v1
    auth_password: organizationweb-auth-password-v1
    rabbitmq_username: organizationweb-rabbitmq-username-v1
    rabbitmq_password: organizationweb-rabbitmq-password-v1
    rabbitmq_config: organizationweb-rabbitmq-config-v1
