---
platform_environment: production
platform_release_version: 0.1.0
platform_public_ipv4: 159.195.156.57
platform_public_interface: eth0
platform_swarm_data_path_port: 4789
platform_swarm_default_addr_pool:
  - 10.0.0.0/8
platform_swarm_default_addr_pool_mask_length: 24
platform_install_root: /opt/dockerswarm
platform_state_root: /srv/dockerswarm
platform_edge_network: apptolast-edge
platform_public_tcp_ports:
  - 80
  - 443
edge_cloudflare_zone: apptolast.com
edge_traefik_hostname: edge.apptolast.com
