---
- name: Deploy the Traefik edge stack
  hosts: swarm_managers
  become: true
  gather_facts: true
  serial: 1
  any_errors_fatal: true

  vars_files:
    - ../../config/platform.yml
    - ../group_vars/all.yml

  roles:
    - role: edge
    - role: deployment_metadata
